name: 'Remind PR Review'
description: 'Remind PR review requests by sending a slack DM'
branding:
  icon: "bell"
  color: "green"
inputs:
  token:
    description: "GitHub token"
    required: true
  slackBotToken:
    description: "slack bot token for messaging"
    required: true
  githubEmailToSlack:
    description: "github email to slack member id mapping, in the format of email:slack_id"
    required: false
    default: ""
runs:
  using: 'node20'
  main: 'dist/index.js'