name: 'PR Due Label Manager'
description: 'Manages PR due date labels (D-3 to D-0)'
branding:
  icon: 'bell'
  color: 'green'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
