name: 'Claude Django Code Review'
description: 'AI-powered Django code review using Claude'
author: 'drtail'

inputs:
  anthropic_api_key:
    description: 'Anthropic API Key'
    required: true
  github_token:
    description: 'GitHub Token for PR operations'
    required: true
  model:
    description: 'Claude model to use for code review'
    required: false
    default: 'claude-sonnet-4-6'
  review_language:
    description: 'Language for review output'
    required: false
    default: 'Korean'
  trigger_label:
    description: 'Label name that triggers the review'
    required: false
    default: '🤖 AI Review'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Minimize previous PR comments
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            per_page: 100
          });

          for (const comment of comments.data) {
            if (comment.body && comment.body.includes('Claude Django Code Review')) {
              try {
                await github.graphql(`
                  mutation($id: ID!) {
                    minimizeComment(input: {subjectId: $id, classifier: OUTDATED}) {
                      clientMutationId
                    }
                  }
                `, { id: comment.node_id });
                console.log(`Minimized comment ${comment.id} by ${comment.user.login}`);
              } catch (error) {
                console.log(`Failed to minimize comment ${comment.id}: ${error.message}`);
              }
            }
          }

    - name: Generate Django Code Review
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        show_full_output: true
        prompt: |
          REPO: ${{ github.repository }}
          PR NUMBER: ${{ github.event.pull_request.number }}

          You are a senior Django backend engineer reviewing this PR.
          First, read the project's CLAUDE.md file (if it exists) to understand project-specific conventions, architecture patterns, and coding standards. Apply those conventions throughout your review.

          **Critical Analysis Areas (in priority order):**

          1. **Database Query Efficiency (HIGHEST PRIORITY):**
             - Trace complete query execution paths: ViewSet.queryset → Serializer → nested Serializers → SerializerMethodField
             - Identify ALL N+1 queries by checking every ForeignKey/relation access
             - Verify select_related/prefetch_related coverage matches actual usage
             - Check for inefficient patterns: redundant queries, unnecessary count(), missing bulk operations
             - Analyze queryset usage in EACH view method separately
             - Test passing does NOT prove query efficiency — recommend query count assertions where missing

          2. **Architecture (per project conventions):**
             - Check CLAUDE.md for the project's layer responsibilities (e.g., views, serializers, services/usecases, tasks)
             - Verify business logic is placed in the correct layer
             - Flag any layer boundary violations

          3. **Security:**
             - Authentication/permission gaps
             - SQL injection, XSS risks
             - Sensitive data exposure

          4. **Test Quality:**
             - Follow project-specific test conventions from CLAUDE.md
             - Check for proper exception handling assertions
             - Verify use of model enums instead of hardcoded strings
             - Verify coverage of key status codes (200, 400, 401, 403, 404)

          **Priority Levels (Pn Rule):**
          - **P1**: Critical bugs - security vulnerabilities, data loss, crashes (MUST fix)
          - **P2**: Convention violations, performance issues requiring improvement (SHOULD fix)
          - **P3**: Suggested improvements, better practices (COULD fix)
          - **P4**: Minor suggestions, style preferences (CONSIDER)
          - **P5**: Nitpicks, optional enhancements (FYI)

          **Review Decision Criteria:**
          - P1 or P2 issues found → REQUEST_CHANGES
          - Only P3-P5 issues found → COMMENT
          - All good → APPROVE

          **Output Requirements:**
          - Write entire review in ${{ inputs.review_language }}
          - Start with review decision header (## ❌ REQUEST CHANGES / ## 💬 COMMENT / ## ✅ APPROVED)
          - Format each review item with the following structure:
            * `[Pn]` badge + descriptive title summarizing the issue
            * Include file:line reference and detailed explanation in the body
            * Group related items under category headings
          - End with conclusion section restating the decision
          - Example structure:
              ```
              ## ❌ REQUEST CHANGES

              <Brief summary of why changes are requested>

              ---

              ### <Category>

              `[P2]` **<Issue title>**
              `path/to/file.py:45` - <Explanation>

              `[P2]` **<Issue title>**
              `path/to/file.py:123` - <Explanation>

              ### <Category>

              `[P3]` **<Issue title>**
              `path/to/file.py:20` - <Explanation>

              ---

              ## <Conclusion header restating the decision>

              <Summary of issue counts and next steps>
              ```
          - Do NOT mention "CLAUDE.md" in your review output
          - Explain conventions directly as standard practices
          - Provide concrete code examples where helpful
          - For query issues, trace the complete execution path with line numbers

          **Self-Check Before Finalizing:**
          Before saving, verify your own review:
          - Re-read the PR diff and confirm every changed file is covered
          - Confirm all database queries are traced end-to-end
          - Confirm no security issues were overlooked
          - Confirm file:line references are accurate

          IMPORTANT: Never write files to /tmp/ or any directory outside the repository root. All file operations must use relative paths in the current working directory.

          Save your ${{ inputs.review_language }} review to a file named '.claude-code-review.md' using Write tool. Do NOT post to PR yet.

        claude_args: '--model ${{ inputs.model }} --allowed-tools "Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*),Write,Read,Glob,Grep"'

    - name: Post Review to PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');

          let review;
          try {
            review = fs.readFileSync('.claude-code-review.md', 'utf8');
          } catch (error) {
            console.error('Failed to read .claude-code-review.md:', error);
            core.setFailed('Review file not found. Claude review may have failed.');
            return;
          }

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `## Claude Django Code Review\n\n${review}`
          });

          console.log('Review posted successfully');

    - name: Remove AI Review label
      if: success()
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          try {
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: '${{ inputs.trigger_label }}'
            });
            console.log('Removed "${{ inputs.trigger_label }}" label after successful review');
          } catch (error) {
            console.log(`Failed to remove label: ${error.message}`);
          }

    - name: Cleanup review files
      if: always()
      shell: bash
      run: |
        rm -f .claude-code-review*.md
        echo "Cleaned up review files"
