name: Release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Install and build each action
        run: |
          for dir in $(find . -type d \( -exec test -f '{}/package.json' \; -a -exec test -d '{}/src' \; -a \( -exec test -f '{}/action.yml' \; -o -exec test -f '{}/action.yaml' \; \) \) -print); do
            cd $dir
            pnpm install
            pnpm build
            cd -
          done


      - name: Add to tag
        run: |
          current_tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "Current tag is $current_tag"
          if [[ ! $current_tag == v* ]]; then
            echo "Tag name should start with v but was $current_tag"
            exit 1
          fi
          major_tag=$(echo $current_tag | cut -d. -f1)
          echo "Major tag is $major_tag"

          sed -i -E 's|^/?dist/?||g' .gitignore
          rm -fr .github/workflows

          git add .
          if [[ -z $(git status --porcelain) ]]; then
            echo "Current tag is up-to-date"
            exit 0
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Release $current_tag"
          git tag -f $current_tag
          git tag -f $major_tag
          git push origin -f $current_tag $major_tag

