name: notify pr review

on:
  pull_request:
    types: [review_requested]
    
jobs:
  notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable pnpm
      - name: Install dependencies
        run: cd remind-pr-review && pnpm install
      - name: Build
        run: cd remind-pr-review && pnpm build
      - name: Test Notify PR Review
        uses: ./remind-pr-review
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}